language: node_js
node_js:
  - node

env:
  matrix:
    secure: OBdSqjZB1Oxe9s/J/dRFTzblMsfSMux2Z6ON+5Kw4xchzpITRR1eLN6JmYTBZVlXJhoWibbqK7I/ZO3SgsVxGk9/+FTsGJxRzNV9lhEqhPbRtwoeV2aTjIa3Oj41dEx/7o1tFXchLHgCzBQfZTXaJ0XhHO0jBEaRqqb0hT6sP6wE0QerHmtD9DowTBQXi0NDTiK4gHc9N2xkhlR/ZU5GeAYzaPMTihacqaM4TcH4eEckLqhOosMsqp30QGzmxduLlrKkT9aRL78tLw4UCFvA6joo6zA/NHpNPkhWS7A3NOdpw/53NU9qVfogPvWhKHwW0Yz/bRTJ36oEuHNf5sgJLw7h0Ku7JqIklRCU1v0gMg1a5dRoHmT6IACcQw+TploiFVjKTnJ2r2pogI13NHZhuRawLekM4/CVBEHHHvsQyJBM0lsP3dWx3PPNON00nc449+2MSTyYD08HdpQUHnNzZ8XGo5mDbHQnANQaz1xykp6qT0RYrZueTx+WkIlcgVE2PdLm01e/mDSfuGGD47XSEM7APg0BQne4PPc4KSv/H7/PwoxEBbhUZ9/vDkbqcFVyIlvg6Ys42fy8OHwkZsKMKoa+sG75SY5R2ln9gTdSX+ELydREaZXyGbJngrHT7vqAUrljH7AGJgt6gqZ1pPJhq5bFcPDb3TU8XrQgR13ir18=

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: master
  on:
    branch: release
    tags: true
